"""Structured plan types shared across all planner implementations."""

from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import Enum
from typing import Any


class AttackPhase(Enum):
    RECON = "recon"
    AUDIT = "audit"
    EXPLOIT = "exploit"
    REPORT = "report"


class PlanStatus(Enum):
    DRAFT = "draft"
    APPROVED = "approved"
    RUNNING = "running"
    PAUSED = "paused"
    COMPLETED = "completed"
    FAILED = "failed"


@dataclass
class TokenAssessment:
    """AI's evaluation of the captured token's power and reach."""

    power_level: str  # root | admin | privileged | standard | restricted
    summary: str
    accessible_paths: list[str] = field(default_factory=list)
    escalation_possible: bool = False


@dataclass
class PlannedStep:
    """A single attack step in the plan."""

    tool: str  # MCP tool name, e.g. "run_capability_audit"
    reason: str
    params: dict[str, Any] = field(default_factory=dict)
    priority: int = 1
    expected_impact: str = ""
    phase: AttackPhase = AttackPhase.AUDIT
    risk: str = "read_only"
    # Conditional execution
    on_failure: str = "abort"  # abort | skip | retry
    alternative_tool: str | None = None
    max_retries: int = 1


@dataclass
class PentestPlan:
    """Full attack plan generated by an AI planner."""

    id: str = field(default_factory=lambda: str(uuid.uuid4())[:8])
    vault_addr: str = ""
    token_assessment: TokenAssessment | None = None
    risk_level: str = "medium"  # critical | high | medium | low
    dynamic_policies: list[str] = field(default_factory=list)
    steps: list[PlannedStep] = field(default_factory=list)
    attack_narrative: str = ""
    thinking: str = ""  # raw model reasoning (audit trail)
    status: PlanStatus = PlanStatus.DRAFT
    created_at: str = field(
        default_factory=lambda: datetime.now(timezone.utc).isoformat()
    )
    current_step_index: int = 0

    @property
    def completed_steps(self) -> int:
        return self.current_step_index

    @property
    def total_steps(self) -> int:
        return len(self.steps)

    @property
    def next_step(self) -> PlannedStep | None:
        if self.current_step_index < len(self.steps):
            return self.steps[self.current_step_index]
        return None

    @property
    def is_done(self) -> bool:
        return self.status in (PlanStatus.COMPLETED, PlanStatus.FAILED)

    def to_dict(self) -> dict[str, Any]:
        """Serialise to a JSON-safe dict."""
        return {
            "id": self.id,
            "vault_addr": self.vault_addr,
            "token_assessment": {
                "power_level": self.token_assessment.power_level,
                "summary": self.token_assessment.summary,
                "accessible_paths": self.token_assessment.accessible_paths,
                "escalation_possible": self.token_assessment.escalation_possible,
            }
            if self.token_assessment
            else None,
            "risk_level": self.risk_level,
            "dynamic_policies": self.dynamic_policies,
            "steps": [
                {
                    "tool": s.tool,
                    "reason": s.reason,
                    "params": s.params,
                    "priority": s.priority,
                    "expected_impact": s.expected_impact,
                    "phase": s.phase.value,
                    "risk": s.risk,
                    "on_failure": s.on_failure,
                    "alternative_tool": s.alternative_tool,
                    "max_retries": s.max_retries,
                }
                for s in self.steps
            ],
            "attack_narrative": self.attack_narrative,
            "thinking": self.thinking,
            "status": self.status.value,
            "created_at": self.created_at,
            "current_step_index": self.current_step_index,
        }

    @classmethod
    def from_dict(cls, data: dict[str, Any]) -> PentestPlan:
        """Deserialise from a JSON-safe dict."""
        plan = cls(
            id=data.get("id", ""),
            vault_addr=data.get("vault_addr", ""),
            risk_level=data.get("risk_level", "medium"),
            dynamic_policies=data.get("dynamic_policies", []),
            attack_narrative=data.get("attack_narrative", ""),
            thinking=data.get("thinking", ""),
            status=PlanStatus(data.get("status", "draft")),
            created_at=data.get("created_at", ""),
            current_step_index=data.get("current_step_index", 0),
        )
        if data.get("token_assessment"):
            ta = data["token_assessment"]
            plan.token_assessment = TokenAssessment(
                power_level=ta.get("power_level", "unknown"),
                summary=ta.get("summary", ""),
                accessible_paths=ta.get("accessible_paths", []),
                escalation_possible=ta.get("escalation_possible", False),
            )
        if data.get("steps"):
            plan.steps = [
                PlannedStep(
                    tool=s.get("tool", ""),
                    reason=s.get("reason", ""),
                    params=s.get("params", {}),
                    priority=s.get("priority", 1),
                    expected_impact=s.get("expected_impact", ""),
                    phase=AttackPhase(s.get("phase", "audit")),
                    risk=s.get("risk", "read_only"),
                    on_failure=s.get("on_failure", "abort"),
                    alternative_tool=s.get("alternative_tool"),
                    max_retries=s.get("max_retries", 1),
                )
                for s in data["steps"]
            ]
        return plan
